# Generated by Django 6.0.6 on 2026-07-10 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('CourseID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('Subject', models.CharField(max_length=50)),
                ('NumberOfSteps', models.SmallIntegerField()),
                ('CreatedDate', models.DateField(auto_now_add=True)),
                ('IsDeleted', models.BooleanField()),
                ('CreatorID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsAndCourses',
            fields=[
                ('SACID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CurrentProgress', models.SmallIntegerField()),
                ('Completed', models.BooleanField()),
                ('CompletedDate', models.DateField(auto_now=True)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.courses')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
