# Generated by Django 6.0.6 on 2026-08-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsuser',
            name='userType',
            field=models.SmallIntegerField(null=True),
        ),
    ]
