# Generated by Django 6.0.6 on 2026-08-05 09:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lmsuser_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lmsuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
