# Generated by Django 6.0.6 on 2026-08-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lmsuser_id_alter_lmsuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lmsuser',
            managers=[
            ],
        ),
    ]
